## Naive Bayes

В этом задании вы сможете немного расслабиться после реализации случайного леса и градиентного бустинга по мотивам материалов прошлой недели. Все, что нужно будет делать — запускать методы из sklearn. Вам предлагается выяснить, какое распределение лучше использовать в наивном байесовском классификаторе в зависимости от вида признаков.

In [52]:
import pandas as pd

from sklearn.datasets import load_digits, load_breast_cancer
from sklearn.model_selection import cross_val_score

from sklearn.naive_bayes import BernoulliNB, CategoricalNB, ComplementNB, GaussianNB, MultinomialNB

Загрузите датасеты digits и breast_cancer из sklearn.datasets. Выведите несколько строчек из обучающих выборок и посмотрите на признаки. С помощью sklearn.cross_validation.cross_val_score c настройками по умолчанию и вызова метода mean() у возвращаемого этой функцией numpy.ndarray, сравните качество работы наивных байесовских классификаторов на этих двух датасетах. Для сравнения предлагается использовать BernoulliNB, MultinomialNB и GaussianNB. Насколько полученные результаты согласуются с рекомендациями из лекций?

In [13]:
digits = load_digits()
cancer = load_breast_cancer()

In [20]:
digits.data[:1]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [23]:
digits.feature_names[:5]

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4']

In [21]:
cancer.data[:1]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [24]:
cancer.feature_names[:5]

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness'], dtype='<U23')

##### Вопрос 1

Каким получилось максимальное качество классификации на датасете breast_cancer?

In [65]:
cancer_cross_score = {}

In [66]:
model = ComplementNB()
cancer_cross_score['ComplementNB'] = cross_val_score(model, cancer.data, cancer.target).mean()

In [67]:
model = GaussianNB()
cancer_cross_score['GaussianNB'] = cross_val_score(model, cancer.data, cancer.target).mean()

In [68]:
model = MultinomialNB()
cancer_cross_score['MultinomialNB'] = cross_val_score(model, cancer.data, cancer.target).mean()

In [69]:
model = BernoulliNB()
cancer_cross_score['BernoulliNB'] = cross_val_score(model, cancer.data, cancer.target).mean()

In [70]:
pd.DataFrame(cancer_cross_score.values(), cancer_cross_score.keys(), columns=['SCORE']).sort_values(by='SCORE')

SCORE
BernoulliNB    0.627418
MultinomialNB  0.896320
ComplementNB   0.896320
GaussianNB     0.938519

In [74]:
with open('1_question.txt', 'w') as f:
    f.write('0.938519')

##### Вопрос 2

Каким получилось максимальное качество классификации на датасете digits?

In [53]:
digit_cross_score = {}

In [54]:
model = ComplementNB()
digit_cross_score['ComplementNB'] = cross_val_score(model, digits.data, digits.target).mean()

In [55]:
model = GaussianNB()
digit_cross_score['GaussianNB'] = cross_val_score(model, digits.data, digits.target).mean()

In [56]:
model = MultinomialNB()
digit_cross_score['MultinomialNB'] = cross_val_score(model, digits.data, digits.target).mean()

In [57]:
model = BernoulliNB()
digit_cross_score['BernoulliNB'] = cross_val_score(model, digits.data, digits.target).mean()

In [64]:
pd.DataFrame(digit_cross_score.values(), digit_cross_score.keys(), columns=['SCORE']).sort_values(by='SCORE')

SCORE
ComplementNB   0.794661
GaussianNB     0.806928
BernoulliNB    0.824174
MultinomialNB  0.870350

In [75]:
with open('2_question.txt', 'w') as f:
    f.write('0.870350')

##### Вопрос 3

Выберите верные утверждения и запишите их номера через пробел (в порядке возрастания номера):

1) На вещественных признаках лучше всего сработал наивный байесовский классификатор с распределением Бернулли

2) На вещественных признаках лучше всего сработал наивный байесовский классификатор с мультиномиальным распределением

3) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными значениями признаков

4) На вещественных признаках лучше всего сработало нормальное распределение
Как отправить

Когда работа будет готова, вы можете загрузить файлы для каждой части задания на вкладке 'Мои работы'.

In [78]:
digits.data[:1]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [79]:
cancer.data[:1]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [80]:
with open('3_question.txt', 'w') as f:
    f.write('3 4')